-- Every city and area the app offers must exist in the database, or members there can't save an area (and can't go live).
with wanted(city_slug, city_name, area_slug, area_name, sort_order) as (values
('nairobi','Nairobi','westlands','Westlands',0),
('nairobi','Nairobi','kilimani','Kilimani',1),
('nairobi','Nairobi','kileleshwa','Kileleshwa',2),
('nairobi','Nairobi','lavington','Lavington',3),
('nairobi','Nairobi','cbd','CBD',4),
('nairobi','Nairobi','south-b','South B',5),
('nairobi','Nairobi','karen','Karen',6),
('nairobi','Nairobi','parklands','Parklands',7),
('nairobi','Nairobi','thika-road','Thika Road',8),
('mombasa','Mombasa','nyali','Nyali',0),
('mombasa','Mombasa','bamburi','Bamburi',1),
('mombasa','Mombasa','old-town','Old Town',2),
('mombasa','Mombasa','kizingo','Kizingo',3),
('kisumu','Kisumu','milimani','Milimani',0),
('kisumu','Kisumu','mamboleo','Mamboleo',1),
('kisumu','Kisumu','cbd','CBD',2),
('kisumu','Kisumu','kondele','Kondele',3),
('nakuru','Nakuru','section-58','Section 58',0),
('nakuru','Nakuru','milimani','Milimani',1),
('nakuru','Nakuru','london','London',2),
('nakuru','Nakuru','cbd','CBD',3),
('eldoret','Eldoret','elgon-view','Elgon View',0),
('eldoret','Eldoret','pioneer','Pioneer',1),
('eldoret','Eldoret','west-indies','West Indies',2),
('eldoret','Eldoret','cbd','CBD',3),
('thika','Thika','makongeni','Makongeni',0),
('thika','Thika','boma','Boma',1),
('thika','Thika','kiandutu','Kiandutu',2),
('thika','Thika','cbd','CBD',3),
('machakos','Machakos','mjini','Mjini',0),
('machakos','Machakos','katoloni','Katoloni',1),
('machakos','Machakos','kalama','Kalama',2),
('machakos','Machakos','cbd','CBD',3),
('kitale','Kitale','milimani','Milimani',0),
('kitale','Kitale','hospital','Hospital',1),
('kitale','Kitale','section-six','Section Six',2),
('kitale','Kitale','cbd','CBD',3),
('kakamega','Kakamega','milimani','Milimani',0),
('kakamega','Kakamega','amalemba','Amalemba',1),
('kakamega','Kakamega','shirere','Shirere',2),
('kakamega','Kakamega','cbd','CBD',3),
('kisii','Kisii','mwembe','Mwembe',0),
('kisii','Kisii','nyanchwa','Nyanchwa',1),
('kisii','Kisii','university','University',2),
('kisii','Kisii','cbd','CBD',3),
('nyeri','Nyeri','ruringu','Ruring’u',0),
('nyeri','Nyeri','kingongo','King’ong’o',1),
('nyeri','Nyeri','whitehouse','Whitehouse',2),
('nyeri','Nyeri','cbd','CBD',3),
('meru','Meru','milimani','Milimani',0),
('meru','Meru','makutano','Makutano',1),
('meru','Meru','gakoromone','Gakoromone',2),
('meru','Meru','cbd','CBD',3),
('malindi','Malindi','casuarina','Casuarina',0),
('malindi','Malindi','maweni','Maweni',1),
('malindi','Malindi','silversands','Silversands',2),
('malindi','Malindi','cbd','CBD',3),
('naivasha','Naivasha','karagita','Karagita',0),
('naivasha','Naivasha','kihoto','Kihoto',1),
('naivasha','Naivasha','lake-view','Lake View',2),
('naivasha','Naivasha','cbd','CBD',3),
('kericho','Kericho','milimani','Milimani',0),
('kericho','Kericho','township','Township',1),
('kericho','Kericho','brookside','Brookside',2),
('kericho','Kericho','cbd','CBD',3),
('embu','Embu','dallas','Dallas',0),
('embu','Embu','blue-valley','Blue Valley',1),
('embu','Embu','majengo','Majengo',2),
('embu','Embu','cbd','CBD',3),
('nanyuki','Nanyuki','milimani','Milimani',0),
('nanyuki','Nanyuki','likii','Likii',1),
('nanyuki','Nanyuki','sports','Nanyuki Sports',2),
('nanyuki','Nanyuki','cbd','CBD',3),
('garissa','Garissa','township','Township',0),
('garissa','Garissa','bulla-iftin','Bulla Iftin',1),
('garissa','Garissa','medina','Medina',2),
('garissa','Garissa','cbd','CBD',3),
('kitui','Kitui','kalundu','Kalundu',0),
('kitui','Kitui','miambani','Miambani',1),
('kitui','Kitui','township','Township',2),
('kitui','Kitui','cbd','CBD',3),
('homa-bay','Homa Bay','sofia','Sofia',0),
('homa-bay','Homa Bay','makongeni','Makongeni',1),
('homa-bay','Homa Bay','shauri-yako','Shauri Yako',2),
('homa-bay','Homa Bay','cbd','CBD',3),
('migori','Migori','oruba','Oruba',0),
('migori','Migori','namba','Namba',1),
('migori','Migori','nyasare','Nyasare',2),
('migori','Migori','cbd','CBD',3)
),
new_cities as (
  insert into public.locations (kind, name, slug, country_code, sort_order)
  select distinct 'city'::location_kind, w.city_name, w.city_slug, 'KE', 100
  from wanted w
  where not exists (select 1 from public.locations l where l.kind = 'city' and l.slug = w.city_slug)
  returning id, slug
),
cities as (
  select id, slug from public.locations where kind = 'city'
  union all
  select id, slug from new_cities
)
insert into public.locations (kind, parent_id, name, slug, country_code, sort_order)
select 'area'::location_kind, c.id, w.area_name, w.area_slug, 'KE', w.sort_order
from wanted w join cities c on c.slug = w.city_slug
where not exists (
  select 1 from public.locations l where l.kind = 'area' and l.parent_id = c.id and l.slug = w.area_slug
);
